[project]
name = 'Ethical-Trade-Certifier'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.premium-distribution]
path = 'contracts/premium-distribution.clar'
clarity_version = 3
epoch = 'latest'

[contracts.producer-verification]
path = 'contracts/producer-verification.clar'
clarity_version = 3
epoch = '3.2'

[contracts.supply-chain-audit]
path = 'contracts/supply-chain-audit.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
